services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  mongo-db:
    container_name: mongo
    image: mongo:6.0.6
    restart: always
    volumes:
      - mongo-db:/data/db
      - ./mongodb_create_user.js:/docker-entrypoint-initdb.d/mongodb_create_user.js
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

      MONGO_USER: analytics_service
      MONGO_PASSWORD: password
      MONGO_DATABASE: mongo-db

networks:
  postgres:
    driver: bridge

volumes:
  mongo-db:
  postgres:
  pgadmin: