server:
  port: 8082

spring:
  application:
    name: user-notification

telegram:
  bot:
    username: JobFlowEnginebot
    token: 6450752222:AAGwpQ7pwAeBLHHGpY6idKuHNR0oTWkEXE4
logging:
  level:
    root: INFO