server:
  port: 8081

spring:
  application:
    name: vacancy-storage

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true