server:
  port: 8083

spring:
  application:
    name: analytics-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true